source 'https://rubygems.org'
ruby '2.5.5'
gem 'sinatra', '~> 2.2.3', require: false

group :test do
  gem 'activemodel'
  gem 'rspec'
  gem 'rack-test'
  gem 'codacy-coverage', :require => false
end
